server {
    root /usr/share/nginx/html;
    error_page 404 /404.html;
    gzip_static on;

    server_name _;
    listen 8080;
    listen [::]:8080;

    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}